version: '3.8'

services:
  db:
    image: postgres:16
    container_name: gopportunities-db
    restart: always
    environment:
      POSTGRES_USER: gopportunities
      POSTGRES_PASSWORD: gopass
      POSTGRES_DB: gopportunities
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
